# Generated by Django 3.2.9 on 2021-12-31 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagsarticle',
            old_name='base',
            new_name='is_main',
        ),
    ]
